# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicsharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='id',
        ),
        migrations.AddField(
            model_name='music',
            name='picture',
            field=models.ImageField(default='music_image/default.jpg', upload_to='music_image'),
        ),
        migrations.AddField(
            model_name='music',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=160, primary_key=True, serialize=False),
        ),
    ]
