# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import musicsharing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicsharing', '0002_auto_20160323_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='content',
            field=models.FileField(upload_to='music', validators=[musicsharing.models.validate_music_file]),
        ),
    ]
