# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 05:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicsharing', '0004_music_lyric'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('name', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('picture', models.ImageField(null=True, upload_to='list_image')),
                ('intro', models.CharField(max_length=300, null=True)),
                ('music', models.ManyToManyField(to='musicsharing.Music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('G', 'Gay'), ('L', 'Lesbian'), ('B', 'Bisexual'), ('T', 'transgender'), ('D', 'undefined :)')], default='D', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
