# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicsharing', '0005_auto_20160327_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 2, 2, 44, 11, 264855, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
