# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsharing', '0008_auto_20160402_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=160),
        ),
    ]
