# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsharing', '0009_auto_20160402_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='picture',
            field=models.ImageField(default='list_image/default.png', upload_to='list_image'),
        ),
    ]
