# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsharing', '0011_auto_20160402_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='keyword',
            new_name='search_song',
        ),
        migrations.AddField(
            model_name='search',
            name='search_user',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
