# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musicsharing', '0012_auto_20160405_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='add_song',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('G', 'Gay'), ('L', 'Lesbian'), ('B', 'Bisexual'), ('T', 'Transgender'), ('D', 'undefined :)')], default='D', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_song',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_user',
            field=models.CharField(max_length=100),
        ),
    ]
