# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsharing', '0028_auto_20160420_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='lyric',
            field=models.FileField(blank=True, null=True, upload_to='music_lyric'),
        ),
        migrations.AlterField(
            model_name='music',
            name='picture',
            field=models.ImageField(blank=True, default='music_image/default.jpg', upload_to='music_image'),
        ),
    ]
