# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsharing', '0029_auto_20160420_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='intro',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
