# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsharing', '0031_auto_20160420_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
